services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    networks:
      - network

  frontend:
    build: ./frontend/graph_miner_ui
    ports:
      - 5173:80
    networks:
      - network
    depends_on:
      - backend

networks:
  network:
    driver: bridge